import React from 'react';
import Head from 'next/head';
import AppLayout from '@/components/Layout/AppLayout';
import { ChakraProvider } from '@chakra-ui/react';
import { UserProvider } from '@/context/UserContext';
import theme from '@/theme';
import '@fontsource/inter/latin-300.css';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';

export default function App({ Component, pageProps }) {
  const renderWithLayout = Component.getLayout || ((page) => (page));

  return (
    <React.Fragment>
      <Head>
        <title>CuongNV Live Chat</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/chat_icon.png' />
      </Head>
      <ChakraProvider theme={theme}>
        <UserProvider>
          <AppLayout>
            {renderWithLayout(<Component {...pageProps} />)}
          </AppLayout>
        </UserProvider>
      </ChakraProvider>
    </React.Fragment>
  )
}
